import type { Job } from "@/lib/jobs/types";

// Seed job catalog — realistic in STRUCTURE so the platform runs fully without
// any external source/keys. These are illustrative, not live postings; the
// ingestion pipeline (src/lib/jobs/ingestion) replaces these with real sources
// once configured. No secrets. `verification: "unverified"` is honest: seed
// links are examples and not checked.

const POSTED = "2026-06-20T00:00:00.000Z";
const DEADLINE = "2026-07-31T00:00:00.000Z";

function base(): Pick<Job, "postedAt" | "deadline" | "source" | "verification" | "lastCheckedAt"> {
  return {
    postedAt: POSTED,
    deadline: DEADLINE,
    source: "seed",
    verification: "unverified",
    lastCheckedAt: null,
  };
}

export const SEED_JOBS: Job[] = [
  {
    id: "job-med-lab-01",
    slug: "medical-lab-specialist-riyadh",
    title: "أخصائي مختبرات طبية",
    employer: "مجمع طبي خاص",
    sector: "الصحة",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/med-lab-01",
    rawText:
      "مطلوب أخصائي مختبرات طبية، بكالوريوس علوم مختبرات طبية أو أحياء، تصنيف الهيئة السعودية للتخصصات الصحية، خبرة في التحاليل والأحياء الدقيقة.",
    acceptedMajors: ["medical-lab", "biology"],
    acceptsAllMajors: false,
    skills: ["التحاليل المخبرية", "الأحياء الدقيقة", "ضبط الجودة", "تصنيف SCFHS"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-bio-qc-02",
    slug: "quality-control-analyst-jeddah",
    title: "محلل ضبط جودة",
    employer: "شركة أغذية",
    sector: "الصناعة",
    city: "جدة",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/qc-02",
    rawText:
      "محلل ضبط جودة في مختبر، يفضل تخصص أحياء أو كيمياء، إلمام بمعايير السلامة الغذائية والتحاليل المخبرية.",
    acceptedMajors: ["biology", "chemistry"],
    acceptsAllMajors: false,
    skills: ["ضبط الجودة", "سلامة الأغذية", "التحاليل المخبرية"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-acc-03",
    slug: "accountant-riyadh",
    title: "محاسب",
    employer: "شركة مقاولات",
    sector: "المالية",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/acc-03",
    rawText:
      "مطلوب محاسب، بكالوريوس محاسبة، إلمام بالقيود المحاسبية والزكاة والضريبة وإعداد التقارير المالية.",
    acceptedMajors: ["accounting"],
    acceptsAllMajors: false,
    skills: ["القيود المحاسبية", "الزكاة والضريبة", "التقارير المالية", "Excel"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-audit-04",
    slug: "junior-auditor-dammam",
    title: "مدقق حسابات مبتدئ",
    employer: "مكتب مراجعة",
    sector: "المراجعة",
    city: "الدمام",
    workMode: "hybrid",
    applyUrl: "https://example.com/apply/audit-04",
    rawText:
      "مدقق حسابات مبتدئ، تخصص محاسبة أو إدارة مالية، مهارات تحليل ومراجعة، يفضل التوجه لشهادة SOCPA.",
    acceptedMajors: ["accounting", "management"],
    acceptsAllMajors: false,
    skills: ["المراجعة", "التحليل المالي", "الامتثال"],
    suggestedCourses: [],
    suggestedCerts: ["SOCPA"],
    ...base(),
  },
  {
    id: "job-mktg-05",
    slug: "digital-marketing-specialist-remote",
    title: "أخصائي تسويق رقمي",
    employer: "متجر إلكتروني",
    sector: "التجارة الإلكترونية",
    city: "عن بُعد",
    workMode: "remote",
    applyUrl: "https://example.com/apply/mktg-05",
    rawText:
      "أخصائي تسويق رقمي، إدارة حملات السوشيال ميديا والإعلانات، تحليل الأداء، يفضل تخصص تسويق أو إدارة أعمال.",
    acceptedMajors: ["marketing", "management"],
    acceptsAllMajors: false,
    skills: ["التسويق الرقمي", "إدارة الحملات", "تحليل البيانات", "السوشيال ميديا"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-dev-06",
    slug: "frontend-developer-riyadh",
    title: "مطور واجهات أمامية",
    employer: "شركة تقنية",
    sector: "التقنية",
    city: "الرياض",
    workMode: "hybrid",
    applyUrl: "https://example.com/apply/dev-06",
    rawText:
      "مطور واجهات أمامية، تخصص حاسب آلي أو تقنية معلومات، خبرة في JavaScript وReact، مهارات حل المشكلات.",
    acceptedMajors: ["computer"],
    acceptsAllMajors: false,
    skills: ["JavaScript", "React", "HTML/CSS", "Git"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-support-07",
    slug: "it-support-specialist-jeddah",
    title: "أخصائي دعم فني",
    employer: "جهة حكومية",
    sector: "التقنية",
    city: "جدة",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/support-07",
    rawText:
      "أخصائي دعم فني، تخصص حاسب أو تقنية معلومات، معرفة بالشبكات وأنظمة التشغيل ودعم المستخدمين.",
    acceptedMajors: ["computer"],
    acceptsAllMajors: false,
    skills: ["الدعم الفني", "الشبكات", "أنظمة التشغيل"],
    suggestedCourses: [],
    suggestedCerts: ["CompTIA A+"],
    ...base(),
  },
  {
    id: "job-arabic-08",
    slug: "arabic-teacher-makkah",
    title: "معلم لغة عربية",
    employer: "مدارس أهلية",
    sector: "التعليم",
    city: "مكة المكرمة",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/arabic-08",
    rawText:
      "معلم لغة عربية، بكالوريوس لغة عربية، إلمام بالنحو والبلاغة ومهارات التدريس وإدارة الصف.",
    acceptedMajors: ["arabic"],
    acceptsAllMajors: false,
    skills: ["تدريس اللغة العربية", "النحو والبلاغة", "إدارة الصف"],
    suggestedCourses: [],
    suggestedCerts: ["الرخصة المهنية للمعلمين"],
    ...base(),
  },
  {
    id: "job-sharia-09",
    slug: "sharia-researcher-riyadh",
    title: "باحث شرعي",
    employer: "مركز بحثي",
    sector: "البحث",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/sharia-09",
    rawText:
      "باحث شرعي، تخصص شريعة أو دراسات إسلامية، مهارات في الفقه وأصوله والبحث العلمي والتوثيق.",
    acceptedMajors: ["sharia"],
    acceptsAllMajors: false,
    skills: ["البحث الشرعي", "الفقه وأصوله", "التوثيق العلمي"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-hr-10",
    slug: "hr-specialist-riyadh",
    title: "أخصائي موارد بشرية",
    employer: "شركة كبرى",
    sector: "الموارد البشرية",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/hr-10",
    rawText:
      "أخصائي موارد بشرية، يقبل تخصصات إدارة أعمال أو علم نفس أو علم اجتماع، مهارات توظيف وتقييم وتواصل.",
    acceptedMajors: ["management", "psychology", "sociology"],
    acceptsAllMajors: false,
    skills: ["التوظيف", "تقييم الأداء", "التواصل", "أنظمة العمل"],
    suggestedCourses: [],
    suggestedCerts: ["aPHRi"],
    ...base(),
  },
  {
    id: "job-gis-11",
    slug: "gis-coordinator-riyadh",
    title: "منسق نظم معلومات جغرافية",
    employer: "أمانة منطقة",
    sector: "التخطيط العمراني",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/gis-11",
    rawText:
      "منسق نظم معلومات جغرافية GIS، تخصص جغرافيا أو نظم معلومات جغرافية، إعداد الخرائط وتحليل البيانات المكانية.",
    acceptedMajors: ["geography-gis"],
    acceptsAllMajors: false,
    skills: ["ArcGIS", "تحليل مكاني", "إعداد الخرائط", "قواعد البيانات المكانية"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-social-12",
    slug: "social-development-officer-abha",
    title: "أخصائي تنمية اجتماعية",
    employer: "جمعية تنموية",
    sector: "القطاع الاجتماعي",
    city: "أبها",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/social-12",
    rawText:
      "أخصائي تنمية اجتماعية، تخصص علم اجتماع أو علم نفس أو خدمة اجتماعية، مهارات تنظيم برامج مجتمعية.",
    acceptedMajors: ["sociology", "psychology"],
    acceptsAllMajors: false,
    skills: ["العمل المجتمعي", "إدارة البرامج", "التواصل"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-heritage-13",
    slug: "heritage-coordinator-alula",
    title: "منسق تراث ومتاحف",
    employer: "هيئة تراثية",
    sector: "السياحة والتراث",
    city: "العُلا",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/heritage-13",
    rawText:
      "منسق تراث ومتاحف، تخصص تاريخ أو آثار، توثيق المقتنيات وتنظيم المعارض والجولات التعريفية.",
    acceptedMajors: ["history"],
    acceptsAllMajors: false,
    skills: ["توثيق التراث", "تنظيم المعارض", "إدارة المقتنيات"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-admin-14",
    slug: "admin-coordinator-allmajors-riyadh",
    title: "منسق إداري",
    employer: "شركة خدمات",
    sector: "الإدارة",
    city: "الرياض",
    workMode: "onsite",
    applyUrl: "https://example.com/apply/admin-14",
    rawText:
      "منسق إداري، يقبل جميع التخصصات، مهارات تنظيم وحفظ ملفات وتواصل وإجادة الحاسب.",
    acceptedMajors: [],
    acceptsAllMajors: true,
    skills: ["التنظيم الإداري", "إدارة الملفات", "Microsoft Office", "التواصل"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
  {
    id: "job-cs-15",
    slug: "customer-service-allmajors-remote",
    title: "ممثل خدمة عملاء",
    employer: "شركة اتصالات",
    sector: "خدمة العملاء",
    city: "عن بُعد",
    workMode: "remote",
    applyUrl: "https://example.com/apply/cs-15",
    rawText:
      "ممثل خدمة عملاء، متاح لجميع التخصصات، مهارات تواصل وحل مشكلات والعمل بنظام الورديات.",
    acceptedMajors: [],
    acceptsAllMajors: true,
    skills: ["خدمة العملاء", "التواصل", "حل المشكلات"],
    suggestedCourses: [],
    suggestedCerts: [],
    ...base(),
  },
];
